CREATE DATABASE TestDBLibro
GO
USE TestDBLibro
GO
CREATE TABLE LIBRO(
	LibroId INT NOT NULL PRIMARY KEY IDENTITY,
	Nombre VARCHAR(150) NOT NULL UNIQUE,
	Descripcion VARCHAR(300),
	Autor VARCHAR(150),
	FechaDePublicacion DATETIME,
	NumeroDeEjemplares INT,
	Costo DECIMAL(10,4)
)
GO
SELECT * FROM LIBRO